spring.application.name=Music_Playlist
springdoc.api-docs.path=/v3/api-docs

# DATABASE
spring.datasource.url=jdbc:h2:file:./data/musicdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 CONSOLE
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# CORS
cors.allowed-origins=http://localhost:3000,http://localhost:5173

spring.mvc.pathmatch.matching-strategy=ant_path_matcher